# Generated by Django 5.0.3 on 2024-03-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MainApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
