# Generated by Django 5.0.3 on 2024-03-29 21:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MainApp", "0003_rename_user_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
