# Generated by Django 5.0.3 on 2024-04-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MainApp", "0006_remove_detailedjob_max_salary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detailedjob",
            name="application_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
