# Generated by Django 5.0.3 on 2024-04-02 17:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MainApp", "0007_alter_detailedjob_application_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detailedjob",
            name="application_url",
        ),
        migrations.RemoveField(
            model_name="detailedjob",
            name="pay_period",
        ),
    ]
