# Generated by Django 5.0.3 on 2024-04-05 21:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MainApp", "0009_cv_experience_preference_resume_study"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experience",
            old_name="job_description",
            new_name="job_detail",
        ),
    ]
