# Generated by Django 5.0.3 on 2024-04-06 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MainApp", "0011_alter_cv_cv_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="job_duration",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
