# Generated by Django 5.0.3 on 2024-04-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MainApp", "0013_school"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="school",
            name="country",
        ),
        migrations.RemoveField(
            model_name="school",
            name="website",
        ),
        migrations.AlterField(
            model_name="school",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
