# Generated by Django 5.0.3 on 2024-04-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MainApp", "0014_remove_school_country_remove_school_website_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
