# Generated by Django 5.0.2 on 2024-04-08 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0017_favoritejob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritejob',
            name='job_type',
        ),
    ]
