# Generated by Django 5.0.3 on 2024-04-02 17:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Authentication", "0002_job_resume"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Job",
        ),
    ]
