# Generated by Django 5.0.3 on 2024-04-04 18:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Authentication", "0004_cv_experience_preference_study"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experience",
            name="user",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="user",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="user",
        ),
        migrations.RemoveField(
            model_name="study",
            name="user",
        ),
        migrations.DeleteModel(
            name="CV",
        ),
        migrations.DeleteModel(
            name="Experience",
        ),
        migrations.DeleteModel(
            name="Preference",
        ),
        migrations.DeleteModel(
            name="Resume",
        ),
        migrations.DeleteModel(
            name="Study",
        ),
    ]
