# Generated by Django 5.0.3 on 2024-04-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "Authentication",
            "0005_remove_experience_user_remove_preference_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
